<a href="https://colab.research.google.com/github/rgspatial/Practicing/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. PyTorch Fundamentals
## Resource: https://www.learnpytorch.io/00_pytorch_fundamentals/
## If  you have question: https://github.com/mrdbourke/pytorch-deep-learning/discussions

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

1.12.0+cu113


## Introduction to Tensors

### Creating tensors 

### PyTorch tensors  are created using torch.Tensor() = https://pytorch.org/docs/stable/tensors.html

In [ ]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# Get tensor back as Python int
scalar.item()

7

In [ ]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# MATRIX
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX


tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],[3,6,9],[2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [ ]:
TENSOR2 = torch.tensor([[[[1,5,9],[2,6,8],[1,5,9]]]])
TENSOR2


tensor([[[[1, 5, 9],
          [2, 6, 8],
          [1, 5, 9]]]])

In [ ]:
TENSOR2.ndim

4

In [ ]:
TENSOR2.shape

torch.Size([1, 1, 3, 3])

# Random tensors

## Why random tensors?

### Random tensors are imports bc the way many nueral networks learn is that they start with tensors full of random numbers and then adjust those numbers to better represent the data.

###`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers

#### https://pytorch.org/docs/stable/generated/torch.rand.html

In [ ]:
# Create a randomt tensor of shape (3,4)
random_tensor=torch.rand(3,4)
random_tensor

tensor([[0.0330, 0.3453, 0.3447, 0.8055],
        [0.7701, 0.2512, 0.4756, 0.3642],
        [0.8902, 0.0701, 0.2513, 0.2207]])

In [ ]:
random_tensor.ndim

2

In [ ]:
# Create a randome tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(224,224,3) # height, width, color channels (r,g,b)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

## Zeros and ones

In [ ]:
# Create a tensor  of all zeros
zero = torch.zeros(3,4)

In [ ]:
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zero*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# Create tensor of all ones
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

## Creating a range  of tensors and tensors-like

In [ ]:
# use torch.range()
one_to_ten = torch.arange(start=1,end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)

In [ ]:
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor datatypes
### NOTE: Tensor dtypes isone of big 3 errors.
### 1. Tensors not right dtype
### 2. Tensors not right shape
### 3. Tensors not on the right device

In [ ]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None, # what  dtype is the tensor (e.g. float 32)
                               device=None, # what device tensor on
                               requires_grad=False) # whether or not to track gradients with this tensors  operations
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor*float_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

In [ ]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors (tensor attributes)

1. Tensors not right dtype - to get 'dtype' from a tensor, can use 'tensor.dtype'
2. Tensors not right shape - to get 'shape' from a tensor, can use 'tensor.shape'
3. Tensors not on the right device - to get device from a tensor, can use 'tensor.device'

In [ ]:
# Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[5.0414e-01, 5.0458e-01, 6.6937e-01, 5.3692e-04],
        [3.7565e-01, 6.0041e-01, 3.6358e-01, 9.6749e-01],
        [7.5453e-01, 6.5238e-02, 5.9668e-01, 9.9118e-01]])

In [ ]:
some_tensor.size()

torch.Size([3, 4])

In [ ]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")


tensor([[5.0414e-01, 5.0458e-01, 6.6937e-01, 5.3692e-04],
        [3.7565e-01, 6.0041e-01, 3.6358e-01, 9.6749e-01],
        [7.5453e-01, 6.5238e-02, 5.9668e-01, 9.9118e-01]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include;
- Addition
- Subtraction
- Multiplication (element-wise)
- Division 
- Matrix multiplication

In [ ]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
# Multiply tensor  by 10
tensor * 10


tensor([10, 20, 30])

In [ ]:
tensor

tensor([1, 2, 3])

In [ ]:
# Subtract 10
tensor - 10

tensor([-9, -8, -7])

In [ ]:
# Try out pytorch inbuilt functions
torch.mul(tensor,10)

tensor([10, 20, 30])

In [ ]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix multiplication

Two main ways of performing multiplication in neural networks and  deep learning:
1. Element-wise multiplication
2. Matrix multiplication (dot product)

There  are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must  match:
-(3,2) @ (3,2) - won't work
-(2,3) @ (3,2) - will work
-(3,2) @ (2,3) - will  work

2. The resulting matrix has the shape of the **outer dimensions**:
- (2,3) @ (3,2) -> (2,2)
- (3,2) @ (2,3) -> (3,3)


In [ ]:
# Element wise multiplication
tensor

tensor([1, 2, 3])

In [ ]:
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [ ]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
%%time
value = 0
for i in range (len(tensor)):
  value += tensor[i] * tensor[i]

print(value)

tensor(14)
CPU times: user 5.23 ms, sys: 7 µs, total: 5.24 ms
Wall time: 6.06 ms


In [ ]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 187 µs, sys: 0 ns, total: 187 µs
Wall time: 118 µs


tensor(14)

### One of the most common errors in deep learning: shape errors

In [ ]:
torch.matmul(torch.rand(3,2), torch.rand(2,3))

tensor([[0.1798, 0.3720, 0.2414],
        [0.1234, 0.2059, 0.1722],
        [0.2271, 0.3544, 0.3201]])

In [ ]:
# Shapes for  matrix multiplication
tensor_A = torch.tensor([[1,2],[3,4],[5,6]])
tensor_B = torch.tensor([[7,10],[8,11],[9,12]])

In [ ]:
#torch.mm(tensor_A,tensor_B) # torch.mm is .matmul

RuntimeError: ignored

To fix our tensor shape issues, we can manipulate the shape  of  one of our tensors using a **transpose**

A **transpose** switches the axes or dimensions of a given tensor.

In [ ]:
tensor_B

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

In [ ]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [ ]:
tensor_A

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [ ]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.T.shape}")
print(f"Mulitplying: {tensor_A.shape} @ {tensor_B.T.shape}) <- inner dimensions must match")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\noutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([2, 3])
Mulitplying: torch.Size([3, 2]) @ torch.Size([2, 3])) <- inner dimensions must match
tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

output shape: torch.Size([3, 3])
